#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MonoDroid.ColorPickers.Resource", IsApplication=false)]

namespace MonoDroid.ColorPickers
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public static int color_picker_view = 2130968576;
			
			// aapt resource value: 0x7f040002
			public static int new_color_panel = 2130968578;
			
			// aapt resource value: 0x7f040001
			public static int old_color_panel = 2130968577;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int dialog_color_picker = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030003
			public static int button_color_picker_alpha = 2130903043;
			
			// aapt resource value: 0x7f030002
			public static int button_color_picker_noalpha = 2130903042;
			
			// aapt resource value: 0x7f030004
			public static int button_color_picker_round = 2130903044;
			
			// aapt resource value: 0x7f030000
			public static int dialog_color_picker = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int press_color_to_apply = 2130903041;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
